### ISSUE TITLE
use setMerge() to merge one column ,then delete the column,ERROR

### ISSUE THREAD

**Issue by antdesigner** [jspreadsheet/ce#1240] opened 2020-11-28 02:27 UTC
I use setMerge() to merge one column ,then delete the column,error:    in v4

jexcel.js:4440 Uncaught TypeError: Cannot read property 'removeChild' of null
    at Object.obj.deleteColumn (jexcel.js:4440)
    at HTMLDivElement.onclick [as method] (jexcel.js:6753)
    at HTMLDivElement.<anonymous> (jsuites.js:2093)

**Comment by Ruan-Miguel** [comment] 2024-12-20 15:19
Duplicate of #833

**Closed as completed by Ruan-Miguel** 2024-12-20 15:19 UTC
