### ISSUE TITLE
Feature Request: getRowJson(int) function

### ISSUE THREAD

**Issue by akaban01** [jspreadsheet/ce#817] opened 2020-01-11 04:24 UTC
It will great to have getRowJson similar to getJson and getRowData.

**Comment by jabis** [comment] 2020-03-01 09:27
This was a duplicate of previous closed issue, I added a simple snippet there:
 .getRowJson(int) 
https://github.com/paulhodel/jexcel/issues/747#issuecomment-593074725

**Closed as completed** 2020-03-12 17:38 UTC
